### ISSUE TITLE
Looks cool, but what's the exact approximate cost

### ISSUE THREAD

**Issue by huameiwei-vc** [aws-samples/comfyui-on-eks#1]
If you can, can you put out a video explaining it because I really can't understand it....

**Comment by Shellmode** [comment]
Thanks, will update cost analyze soon.

**Comment by TemryL** [comment]
Hi, awesome work thanks! Did you add the cost analysis?

**Comment by Shellmode** [comment]
Here's the cost analysis: [Cost Analysis](https://github.com/aws-samples/comfyui-on-eks?tab=readme-ov-file#cost-analysis)

**Comment by Shellmode** [comment]
Close the issue.
