### ISSUE TITLE
Do you have met with "FailedMount" Errror?

### ISSUE THREAD

**Issue by zhangjunqiang** [aws-samples/comfyui-on-eks#11]
when i make the deployment of comfyui.
"MountVolume.SetUp failed for volume "comfyui-inputs-pv" : rpc error: code = Internal desc = Could not mount "comfyui-inputs-xxxxxxxxxx-us-east-1" at "/var/lib/kubelet/pods/xxxxxxxxxx/volumes/kubernetes.io~csi/comfyui-inputs-pv/mount": Could not check if "/var/lib/kubelet/pods/xxxxxxxxxx/volumes/kubernetes.io~csi/comfyui-inputs-pv/mount" is a mount point: stat /var/lib/kubelet/pods/xxxxxxxxxx/volumes/kubernetes.io~csi/comfyui-inputs-pv/mount: no such file or directory, Failed to read /host/proc/mounts: open /host/proc/mounts: invalid argument"

**Comment by Shellmode** [comment]
mentioned in the README https://github.com/aws-samples/comfyui-on-eks?tab=readme-ov-file#55-deploy-comfyui-deployment-and-service

please refer to the issue https://github.com/awslabs/mountpoint-s3-csi-driver/issues/174

mountpoint-s3-csi-driver will fix it in the next release.

**Comment by zhangjunqiang** [comment]
really thanks
