### ISSUE TITLE
Unable to continue with install: ServiceAccount "s3-csi-driver-sa" in namespace "kube-system" exists

### ISSUE THREAD

**Issue by ande28em** [aws-samples/comfyui-on-eks#2]
When following instructions to install `aws-mountpoint-s3-csi-driver` I'm getting the following error after executing:
Input:
```
helm upgrade --install aws-mountpoint-s3-csi-driver \
    --namespace kube-system \
    aws-mountpoint-s3-csi-driver/aws-mountpoint-s3-csi-driver
```
Output:
```
Release "aws-mountpoint-s3-csi-driver" does not exist. Installing it now.
Error: Unable to continue with install: ServiceAccount "s3-csi-driver-sa" in namespace "kube-system" 
exists and cannot be imported into the current release: invalid ownership metadata;
label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "eksctl";
annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-mountpoint-s3-csi-driver";
annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```

**Comment by Shellmode** [comment]
Thanks for response, I also noticed the problem recently, installation cmd is from https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md, I'll raise an issue for this.

For now, you can run following cmd to install the addon
```
eksctl create addon --name aws-mountpoint-s3-csi-driver --cluster my-cluster --service-account-role-arn arn:aws:iam::111122223333:role/AmazonEKS_S3_CSI_DriverRole --force
```

change `--service-account-role-arn` to your own

Refer to https://docs.aws.amazon.com/eks/latest/userguide/s3-csi.html

I may revise the document later.

**Comment by Shellmode** [comment]
I've revised the doc, please refer to [6.5.4 Deploy EKS S3 CSI Driver](https://github.com/aws-samples/comfyui-on-eks?tab=readme-ov-file#654-deploy-eks-s3-csi-driver).
