### ISSUE TITLE
Is there any guide for AWS beginners?

### ISSUE THREAD

**Issue by fjm-aw** [aws-samples/comfyui-on-eks#5]
This solution assumes that you have already installed, deployed, and are familiar with the following tools:

[AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html): latest version
[eksctl](https://eksctl.io/installation/)
[kubectl](https://kubernetes.io/docs/tasks/tools/)
[Docker](https://docs.docker.com/engine/install/)
[npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm/)
[CDK](https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html): latest version

----

This is too difficult for ComfyUI creators who are new to AWS. Too many tools and don’t know where to start.

**Comment by fjm-aw** [comment]
My local system is Win11.
Until "6.5.1 Build and Push ComfyUI Docker Image" , I see :

> http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
> #0 building with "default" instance using docker driver
> ....

Is it not possible to build Amazon ECR from win11 to linux?
What can I do?

**Comment by Shellmode** [comment]
This solution is aimed at builders who want to set up the ComfyUI platform on AWS. If you just want to use ComfyUI for personal use, you can deploy it locally or find some providers that offer ComfyUI as a service.

**Comment by fjm-aw** [comment]
I used to use Lambda and s3 for applications, mainly with Unity/Win10/Win11/other cross-platform connections, etc.
And I carefully looked at other samples about ComfyUI on aws-samples.
I currently feel that the architecture diagram and description of this project example are what I expect.
But I am really not familiar with EC2, Docker, etc., so I have these questions and confusions.

I have tried to set up ComfyUI locally, but it does not meet the expected project needs because it is unrealistic to flexibly expand the hardware equipment to cope with a large number of production images.
Currently, I am also learning and familiarizing myself with the tools required for the project.

If possible, maybe you can leave a contact information on Discord or something else. It doesn’t matter if it’s inconvenient.
Thanks for your response!

**Comment by Shellmode** [comment]
Sure I'm glad to help, you can send me email.
