### ISSUE TITLE
How long would it take to spin an instance?

### ISSUE THREAD

**Issue by cian0** [aws-samples/comfyui-on-eks#7]
I have a setup of mine that's very manual, it takes around 3minutes time to generate an image from cold boot.

With this solution, how long would it take starting from no instance running?

**Comment by Shellmode** [comment]
It might take around 7~8 minutes from scratch, including the time to start the EC2 instance and pull all the models from S3 to the local instance store. This solution is not designed for rapid scaling out but rather to improve model loading and switching performance.

**Comment by cian0** [comment]
Got it, thanks for clarifying!
