### ISSUE TITLE
LW and GPU Node usage

### ISSUE THREAD

**Issue by Gursehaj** [aws-samples/comfyui-on-eks#8]
I am not able to understand what is the use of the two LW nodes we are creating and according to manifest files, we are only scaling these LW nodes instead of the GPU node. Am I understanding it wrong or is something else is happening that I am missing?

**Comment by Gursehaj** [comment]
What are the addon pods? I can't see pods within AWS console.

**Comment by Shellmode** [comment]
Use command `kubectl get pods -A` to see all pods in all namespaces

**Comment by Gursehaj** [comment]
What direction should I take if I want to use multiple gpus for multiple requests? Is it possible to scale no of gpus within an ec2 instance on demand?

**Comment by edwinwu2014** [comment]
gpu 不会自动扩容？？

**Comment by Gursehaj** [comment]
What I have seen is the requests get queued to single comfyui instance.

**Comment by edwinwu2014** [comment]
> What I have seen is the requests get queued to single comfyui instance.

I have also encountered this problem, feeling that this does not automatically expand the GPU Node

**Comment by Shellmode** [comment]
Please refer to https://github.com/aws-samples/comfyui-on-eks/issues/6

**Comment by Gursehaj** [comment]
I'll try adding a HPA using KEDA to autoscale.

**Comment by edwinwu2014** [comment]
> I'll try adding a HPA using KEDA to autoscale.

Great! Can you share the modified project?
